### ISSUE TITLE
Error in the code for Preference Panel

### ISSUE THREAD

**Issue by orencloud** [CGCookie/blender-addon-updater#91] opened 2024-02-03 14:48 UTC
class DemoPreferences(bpy.types.AddonPreferences):
	bl_idname = __package__
	auto_check_update = bpy.props.BoolProperty(

gave me this error in the blender terminal (same for "updater_interval_months" and all the other ones):
rna_uiItemR: property not found: DemoPreferences.auto_check_update

this fixed it:
auto_check_update : bpy.props.BoolProperty(name="

**Comment by TheDuckCow** [comment] 2024-02-04 17:01
What version of blender are you using?

Trying myself freshly now, I am not seeing any printouts with this repo as-is. Maybe while implementing in your own project, you didn't include the `addon_updater_ops.make_annotations(cls)  # Avoid blender 2.8 warnings.` line in registration? If you skip this then yes, you would indeed get these problems. Be sure to also fully restart blender when testing of course.

We can't directly use syntax like `auto_check_update : bpy.props.BoolProperty(name="` as yields syntax errors in e.g. Python 3.5 (used in blender 2.79). At a certain point it will be fair enough to officially end support for Blender 2.7x, but since nothing is actually broken at this time in 4.0 I don't see a good reason to do so. The `make_annotations` function works around this to after the fact add the annotation attribute to properties so blender 2.8x can function as intended.

**Comment by orencloud** [comment] 2024-02-04 18:13
Sorry, I'm a bit unexperienced with coding. I'm using 4.0.2. My addon will be supported from 3.6 and forward, so I'm not too concerned about retro compatiblity. 

I tried adding the "make annotations" but the terminal still told me that the "auto_check_update" properties couldn't be found. 

The only way to solve it was to switch "=" with ":". 
I noticed it because all my other custom properties used that format. 

Also, thanks a lot for your amazing addon.

**Comment by TheDuckCow** [comment] 2024-02-04 18:35
Ok, no worries - in the end if it works for you, then that's great. We still have other addons that (might) support older versions of blender while also depending on this repo, so I'll close this issue in the meantime. Good luck with your addon, and glad this repo has been of use!On Feb 4, 2024 10:13 AM, orencloud ***@***.***> wrote:
Sorry, I'm a bit unexperienced with coding. I'm using 4.0.2. My addon will be supported from 3.6 and forward, so I'm not too concerned about retro compatiblity.
I tried adding the "make annotations" but the terminal still told me that the "auto_check_update" properties couldn't be found.
The only way to solve it was to switch "=" with ":".
I noticed it because all my other custom properties used that format.
Also, thanks a lot for your amazing addon.

**Closed as completed** 2024-02-04 18:40 UTC
