### ISSUE TITLE
Error with 'include_master' option on

### ISSUE THREAD

**Issue by jdent02** [CGCookie/blender-addon-updater#23] opened 2017-04-24 19:17 UTC
Hi,
I've integrated this updater with the Renderman for Blender addon.  The versioning update works great but I've been seeing some odd behavior when the 'include_master' option is on.

If it is on and the auto update interval has passed, I am prompted to update to the latest master branch.  However when I do that the updater does not install the latest version of master.  Instead it pulls an older version (at least a commit or two prior), thus erasing new features and bugfixes.

However, if I ignore that prompt and manually select 'Master' from the 'install version/old version' dropdown then it will correctly install the latest master.

I haven't made any modifications to the two export modules other than changing the GitHub info and turning 'include_master' on.

Thanks for your help!

**Comment by TheDuckCow** [comment] 2017-04-24 20:49
Thank you for reporting the issue, I will be taking a look at this and hopefully also adding additional configuration feature around being able to install / update from other branches. I'll keep you informed of any updates.

**Comment by bsavery** [comment] 2017-04-24 21:20
Thanks for looking @TheDuckCow .  @jdent02 one thing that might be possible if we could look at the logs when that happens?  Or do we know which commit number it is switching to?

**Comment by jdent02** [comment] 2017-04-24 21:56
I can run a test to see if the logs show anything.  I'm not sure which commit number it's switching to but it was before the holdout stuff and SampleFilter fix added in pull request #485

**Comment by jdent02** [comment] 2017-04-24 21:56
On the Renderman for Blender site BTW

**Comment by jdent02** [comment] 2017-04-25 02:38
So I installed the latest official RfB release (21_3_0) and ran the auto updater.  Here's the log screen of that check:

Check update pressed, first getting current status
Starting background checking thread
BG: Checking for update now in background
Checking for update function
Read in json settings from file
Getting tags from server
Most recent tag found: {'name': 'Master', 'zipball_url': 'https://api.github.com/repos/bsavery/PRMan-for-Blender/zipball/master'}
renderman_for_blender: Wrote out updater json settings to file, with the contents:
{'just_restored': False, 'ignore': False, 'update_ready': False, 'version_text': {}, 'last_check': '2017-04-24 21:31:43.489795', 'backup_date': 'April-24-2017', 'just_updated': False}
No version strings found text:  Master
renderman_for_blender: Wrote out updater json settings to file, with the contents:
{'just_restored': False, 'ignore': False, 'update_ready': True, 'version_text': {'link': 'https://api.github.com/repos/bsavery/PRMan-for-Blender/zipball/v21_3_0', 'version': 'master'}, 'last_check': '2017-04-24 21:31:43.489795', 'backup_date': 'April-24-2017', 'just_updated': False}
BG: Finished checking for update, doing callback

When I click the update to master prompt, it does not appear to update anything, even with a 'inistallation successful' result.  However, if I then manually select 'Master' (note the capitalized first letter) I get this:

Running update
Staging install
Preparing staging folder for download:
 /home/jon/.config/blender/2.78/scripts/addons/PRMan-for-Blender-21_3_0/prman-for-blender-21_3_0_updater/update_staging
Backing up current addon folder
Backup destination path:  /home/jon/.config/blender/2.78/scripts/addons/PRMan-for-Blender-21_3_0/prman-for-blender-21_3_0_updater/backup
renderman_for_blender: Wrote out updater json settings to file, with the contents:
{'just_restored': False, 'ignore': False, 'update_ready': True, 'version_text': {'link': 'https://api.github.com/repos/bsavery/PRMan-for-Blender/zipball/master', 'version': 'master'}, 'last_check': '2017-04-24 21:31:43.489795', 'backup_date': 'April-24-2017', 'just_updated': False}
Now retrieving the new source zip
Starting download update zip
Successfully downloaded update zip
Source folder cleared and recreated
Begin extracting source
Extracted source
renderman_for_blender: Wrote out updater json settings to file, with the contents:
{'just_restored': False, 'ignore': False, 'update_ready': True, 'version_text': {'link': 'https://api.github.com/repos/bsavery/PRMan-for-Blender/zipball/master', 'version': 'master'}, 'last_check': '2017-04-24 21:31:43.489795', 'backup_date': 'April-24-2017', 'just_updated': True}
Restart blender to reload addon and complete update
Running post update callback
Updater returned successful

And the addon updates correctly.

**Comment by jdent02** [comment] 2017-04-25 02:41
I can see the error (the big 'update now' button is linking to 21_3_0 and thinking it's the master branch, whereas the install dropdown finds the correct link).

**Comment by TheDuckCow** [comment] 2017-04-25 03:35
Jon, thanks for this investigation. Let me see what I can do to resolve that, but it sounds like you've isolated the issue. I think it has to do how we have the tags queued internally and where the master object is slotted in, so hopefully will be a quick fix. I'll keep you informed. 

Patrick W. Crawford

**Comment by jdent02** [comment] 2017-04-25 13:20
Thank you!

**Comment by TheDuckCow** [comment] 2017-04-26 02:11
I've been looking at this, and I can see there's some slightly inconsistent logic in place that I'm working to fix. Initially, update to master was intended to be a very simple operation more for developers to easily force installing the master, and is not checking against release versions or timestamps. However as a result, right now when the interval passes it seems to always trigger a popup saying to update to master - even if master has not been further updated. 

So, I have started updating the code to match this behavior: update to master is only done when explicitly pressing on the button in the user preferences panel "install master/old version", while auto-check for update will only check against github release tags - it does not check against the timestamp of the master; thus master is a somewhat "blind" update to latest code committed online while the rest of the addon will continue to allow updated based on releases/tags.

Note I am adding this code description into the _ops.py file, and am working on implementing this:

```
# allow 'master' as an option to update to, regardless of release or version
# default behavior: releases will still be used for auto check (popup),
# but the user has the option from user preferences to directly 
# update to the master branch.
updater.include_master = False

# if using "include_master", 
# updater.include_master_branch defaults to 'master' branch if set to none
# updater.include_master_branch = 'dev' # example targeting another branch
updater.include_master_branch = None

```

I am working on this code today and will keep you updated, changes are being pushed into the dev branch first so what I have pushed may not be production ready yet. I just did the first push but need to do further verification that this resolves all the expected issues. Note with this, the big tall/wide "update" button will *never* say update to master (or any selected branch), instead you are able to only install the latest from a given branch on from the install {branch}/older version button and dropdown.

If instead you are looking for having a popup notification whenever the master branch has been updated, there would be some additional design implications (essentially, that would be resorting to determining updates based on commit timestmaps as opposed to release numbers, requiring a number of changes)

**Comment by jdent02** [comment] 2017-04-26 04:37
I think your proposal will work fine.  Thank you again for the help.

Sent from my iPhone

On Apr 25, 2017, at 9:11 PM, Patrick W. Crawford <notifications@github.com<mailto:notifications@github.com>> wrote:


I've been looking at this, and I can see there's some slightly inconsistent logic in place that I'm working to fix. Initially, update to master was intended to be a very simple operation more for developers to easily force installing the master, and is not checking against release versions or timestamps. However as a result, right now when the interval passes it seems to always trigger a popup saying to update to master - even if master has not been further updated.

So, I have started updating the code to match this behavior: update to master is only done when explicitly pressing on the button in the user preferences panel "install master/old version", while auto-check for update will only check against github release tags - it does not check against the timestamp of the master; thus master is a somewhat "blind" update to latest code committed online while the rest of the addon will continue to allow updated based on releases/tags.

Note I am adding this code description into the _ops.py file, and am working on implementing this:

# allow 'master' as an option to update to, regardless of release or version
# default behavior: releases will still be used for auto check (popup),
# but the user has the option from user preferences to directly
# update to the master branch.
updater.include_master = False

# if using "include_master",
# updater.include_master_branch defaults to 'master' branch if set to none
# updater.include_master_branch = 'dev' # example targeting another branch
updater.include_master_branch = None



I am working on this code today and will keep you updated, changes are being pushed into the dev branch first so what I have pushed may not be production ready yet. I just did the first push but need to do further verification that this resolves all the expected issues. Note with this, the big tall/wide "update" button will never say update to master (or any selected branch), instead you are able to only install the latest from a given branch on from the install {branch}/older version button and dropdown.

If instead you are looking for having a popup notification whenever the master branch has been updated, there would be some additional design implications (essentially, that would be resorting to determining updates based on commit timestmaps as opposed to release numbers, requiring a number of changes)

**Comment by bsavery** [comment] 2017-04-26 13:23
So if I understand what you're getting at to get the latest "master" (or whatever branch include_master_branch is set to) the user would have to manually update?  I suppose that's fine.  In the past we have used the master branch to push quick bug fixes to users.  However It would be more correct to update the release tag for the latest version.  Which would have been harder without an auto updater ;)

Finally, it might be more clear to have have a dropdown in the properties saying "Which branch/tag" do you want to stay on.  You kinda get that through the update to version button.

**Comment by TheDuckCow** [comment] 2017-04-29 15:36
Hello, yes that would be the intended use. If the master option is enabled, users can manually choose to get the "bleeding edge", otherwise releases is the optimal way. The updater supports any number of sub-versions e.g. (1,23,1,1) so you can always resort to that, just name the releases accordingly. 

Agreed, I'll be looking into expanding options for different branches. I'll also say that while right now it doesn't include checking against master most recent update date, it can be something we explore. If we include that feature, one point to bring up is that no matter what the addon would ask the user to "update" after a first install, as the addon itself won't carry information as to what timestamp its code or commit its from. Not that this is a terrible thing, but at least worth pointing out. 

As mentioned, still testing the dev branch but will be ready this weekend for master release.

**Comment by jdent02** [comment] 2017-05-03 16:09
Hi DuckCow,
Do you have an update on when we might be able to give this a spin?  We've got an upcoming version release and it would be awesome to get it in there.

Thanks!

**Comment by TheDuckCow** [comment] 2017-05-03 17:47
Hey, I am adjusting the code base to be more flexible to have multiple branches allowed which involves a few changes, including turning include_masters into an include_branches variable name, and then setting a list of branch options.

I'm hoping to complete this today/tomorrow and release to master. If you need it sooner, [this current commit](https://github.com/CGCookie/blender-addon-updater/tree/cd8a10487963643e57c56b8594489bf199da910c) has functioning and tested code you can use for the update_to_master we discussed above.

Patrick

**Comment by TheDuckCow** [comment] 2017-05-05 08:49
@jdent02 please see the latest release 1.0.3 with the changes spoken of. I have done thorough testing of the system (and now allows you to provide a list of branches you want to include), but please let me know if you run into anything. 

To best update your addon: please completely overwrite both the ops file and the updater python module, basically [re-following this tutorial](http://theduckcow.com/2016/addon-updater-tutorial/). This is because the name of some options have changed (e.g. no longer called `include_master` but rather `include_branches`). Do not just copy-paste over the settings section under the register function, but rather compare what you had before to the settings that exist there now. Again, the main change is around the branches inclusion setting.

**Comment by jdent02** [comment] 2017-05-09 02:26
Thanks DuckCow.  I'll integrate your fixes.  Really appreciate the help (and the addon itself).

**Comment by TheDuckCow** [comment] 2017-05-09 02:27
Sure thing, let me know if you run into any issues - happy to help troubleshoot. Closing issue for now.

**Closed as completed by TheDuckCow** 2017-05-09 02:27 UTC
